export default function TermsPage() {
  return (
    <main className="min-h-screen bg-slate-950 px-6 py-16 text-white">
      <div className="mx-auto max-w-4xl">
        <h1 className="text-4xl font-bold">Terms and Conditions</h1>

        <p className="mt-6 text-slate-300">
          By using QuickToolsHub, you agree to these Terms and Conditions. If
          you do not agree, please do not use this website.
        </p>

        <section className="mt-10">
          <h2 className="text-2xl font-bold">Use of Tools</h2>

          <p className="mt-4 text-slate-300">
            Our tools are provided for general informational, educational, and
            productivity purposes. You are responsible for how you use the
            results generated by our tools.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-bold">No Guarantee</h2>

          <p className="mt-4 text-slate-300">
            We try to provide accurate and useful tools, but we do not guarantee
            that every result will be error-free, complete, or suitable for your
            specific needs.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-bold">User Responsibility</h2>

          <p className="mt-4 text-slate-300">
            You agree not to misuse the website, attempt to damage the service,
            or use the tools for illegal or harmful purposes.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-bold">Limitation of Liability</h2>

          <p className="mt-4 text-slate-300">
            QuickToolsHub is not responsible for any loss, damage, or issue
            caused by using this website or relying on tool results.
          </p>
        </section>

        <section className="mt-10">
          <h2 className="text-2xl font-bold">Changes to Terms</h2>

          <p className="mt-4 text-slate-300">
            We may update these Terms and Conditions at any time. Continued use
            of the website means you accept the updated terms.
          </p>
        </section>
      </div>
    </main>
  );
}